
# Tutorial 2

# Refresh from last week
# what is a boolean? a vector? a dataframe?
# what does the pipe mean?
# install v library
# how do you look up help for a function?

# Download and install a package with a cool dataset
#install.packages('babynames')
library(babynames)

# Load some other packages from last week
library(dplyr)
library(ggplot2)

# Load build-in dataset
data(babynames)

# Exploring data =======================================

# Print to console
babynames

# Easier way to explore:
babynames %>% View

# Reminder: this is a dataframe!

# Check out top and bottom:
babynames %>% head
babynames %>% tail

# Get dimensions
babynames %>% nrow
babynames %>% ncol
babynames %>% dim

# How to look at a single column?
babynames$year
babynames[,1]
babynames[,3]

# Look at range of data in a single column:
babynames$year %>% range

# Look at unique values in a column:
babynames$year %>% unique
babynames$year %>% unique %>% length

# How to look at a single row?
babynames[1,]
babynames[5:10,]

# How to look at a single value?
babynames[2,3]
babynames[20:30,3]

# Filtering data ==============================
# use dplyr to select a certain name (we'll do more detail next week).

# For a single name:
babynames %>% filter(name == 'Keri')

# For multiple names
babynames %>% filter(name %in% c('Keri','Eric'))

# For multiple conditions
babynames %>% filter(name == 'Keri',
                     sex == 'F')

# Save as a new dataframe
keri <- babynames %>% filter(name == 'Keri', sex == 'F')

# Plot! =======================================

# FYI:  R has built-in plot features ...
hist(keri$n)
plot(keri$n ~ keri$year)

# But we are learning a BETTER way ...
library(ggplot2)

# Google Images: ggplot showcase to see the kind of plots you will be able to make

# Talk about the layers of a graph (http://www.datascience.pizza/ggplot.html)

# Initiate a canvas
ggplot()

# Specify your dataset
ggplot(keri)

# Specify your aesthetics
ggplot(keri,
       aes(x=year, y=n))
# (now it knows which axis will represent what, and what the limits will be.)

# Specify your geoms
ggplot(keri,
       aes(x=year, y=n)) +
  geom_line()
# Talk about the plus sign

# You can do all this in the same step:
ggplot(babynames %>% filter(name=='Keri' & sex=='F'),
       aes(x=year, y=n)) +
  geom_line()

# Color-code
ggplot(babynames %>% filter(name=='Keri'),
       aes(x=year, y=n, color=sex)) +
  geom_line()

# Add another person
ggplot(babynames %>% filter(name %in% c('Keri', 'Eric')),
       aes(x=year, y=n, color=name)) +
  geom_line()

# Bah! Let's try this:
ggplot(babynames %>% filter(name %in% c('Keri', 'Eric')),
       aes(x=year, y=n, color=name, lty = sex)) +
  geom_line()

# Rather than retyping this again and again, let's save it as a variable
p <- ggplot(babynames %>% filter(name %in% c('Keri', 'Eric')),
            aes(x=year, y=n, color=name, lty = sex)) +
  geom_line()

# Ask the students to replace Keri and Eric with the names at their table
# and re-save their p object

# Now call it to see the plot
p

# Add some more layers:
p + xlab('Year') + ylab('Children born')

# Re-save as p to carry your updates along:
p <- p + xlab('Year') + ylab('Children born')
p

p <- p + labs(title='U.S. baby names, 1880 - 2020',
       subtitle='Data sourced from the Social Security Administration',
       caption = 'Plot generated by ggplot2, an R package by Hadley Wickham')
p

p <- p + theme_light()

# Install other theme options
#install.packages('ggthemes')
library(ggthemes)
p <- p + theme_economist_white()
p

# Other plot types! =======================================

# Points
ggplot(keri,aes(x=year, y=n)) + geom_point()

# Histograms
ggplot(keri,aes(x=n)) + geom_histogram()

# Violin plot
ggplot(keri,aes(x=name, y=n)) + geom_violin()

# Add other levels
ggplot(babynames %>% filter(name %in% c('Keri','Eric')),
       aes(x=n, fill=name)) + geom_histogram()

ggplot(babynames %>% filter(name %in% c('Keri','Eric')),
       aes(x=name, y=n, fill=name)) + geom_violin()

# Change orientation
ggplot(babynames %>% filter(name %in% c('Keri','Eric')),
       aes(y=name, x=n, fill=name)) + geom_violin()

# For bar charts, use geom_col()
# (adding some names here)
ggplot(babynames %>% filter(name %in% c('Keri','Eric','William','Emily')),
       aes(x=name, y=n, fill=name)) + geom_col()

#...or geom_bar()
ggplot(babynames %>% filter(name %in% c('Keri','Eric','William','Emily')),
       aes(x=name, y=n, fill=name)) +
  geom_bar(stat='identity')

# More complex bar chart
ggplot(babynames %>% filter(name %in% c('Keri','Eric','William','Emily')),
       aes(x=name, y=n, fill=sex)) +
  geom_bar(stat='identity', position = 'dodge')

# Switch orientation,
ggplot(babynames %>% filter(name %in% c('Keri','Eric', 'Emily','William')),
       aes(y=name, x=n, fill=sex)) +
  geom_bar(stat='identity', position = 'dodge')

# Changing colors when color maps to data
ggplot(babynames %>% filter(name %in% c('Keri','Eric','William','Emily')),
       aes(x=name, y=n, fill=sex)) +
  geom_bar(stat='identity', position = 'dodge') +
  scale_fill_manual(values = c('blue', 'grey'))

# Changing color to make it color-independent
ggplot(babynames %>% filter(name %in% c('Keri','Eric','William','Emily')),
       aes(x=name, y=n)) +
  geom_bar(stat='identity', position = 'dodge', fill='firebrick')
# emphasize `aes` concept here


# Scatterplots ! ! ==========================================


# NO MORE BABIES! Let's use some different data.

# Let's make up a dataset
# Code the equation for a linear model
a <- 2
b <- 0
x <- 5
y <- a*x + b
y

# We can put this x and y in a dataframe
df <- data.frame(x,y)
df %>% head

# Then plot it
ggplot(df, aes(x=x, y=y)) + geom_point(alpha=.2)

# But we only have a single point -- boring!
# Lets predict a lot of y's based ona lot of x's
x <- 1:1000
a <- 2
b <- 3
y <- a*x + b
df <- data.frame(x,y)
ggplot(df, aes(x=x, y=y)) + geom_point(alpha=.2)

# K that's better, but still boring.
# Let's add some variation!
e <- rnorm(length(x), mean=0, sd=100)
hist(e)
y <- a*x + b + e
df <- data.frame(x,y)
ggplot(df, aes(x=x, y=y)) + geom_point(alpha=.2)

# Sneak peak to stats week:
df_lm <- lm(y~x, data=df)
summary(df_lm)

# Add smoothed line
ggplot(df, aes(x=x, y=y)) +
  geom_point(alpha=.2) +
  geom_smooth()

# Curved line
x <- 1:1000
a <- 2
b <- 3
c <- 4
e <- rnorm(length(x), mean=0, sd=200000)
y <- a*x^2 + b*x + c + e
df <- data.frame(x,y)
ggplot(df, aes(x=x, y=y)) + geom_point(alpha=.2) + geom_smooth()


# Homework: use the student survey! ! =======================================

# TBD, depending on Keri's thoughts on the tutorial content



